services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5050:5050"
    networks:
      - codex_network
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/codex

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - codex_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://backend:5050
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - codex_network
    volumes:
      - mongo-data:/data/db

networks:
  codex_network:
    driver: bridge 
    

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally
    