services:
  backend:
    build: ./backend
    env_file: .env
    container_name: backend
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - codex_network
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://${MONGO_HOST}:{MONGO_PORT}/${NOM_DATABASE}

  frontend:
    build: ./frontend
    env_file: .env
    container_name: frontend
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - codex_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://backend:5050
  mongo:
    image: mongo:latest
    env_file: .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - codex_network
    volumes:
      - mongo-data:/data/db

networks:
  codex_network:
    driver: bridge 
    

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally
    